name: Deploy Tax Quote Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # Add this for gh-pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install -g pdfjs-dist # Add this for PDF.js worker

      - name: Copy PDF Worker
        run: |
          mkdir -p public/pdfjs # Ensure pdfjs directory exists
          cp node_modules/pdfjs-dist/build/pdf.worker.min.js public/pdfjs/

      - name: Build application
        run: |
          npm run build || exit 1
        env:
          BASE_URL: '/${{ github.event.repository.name }}'
          VITE_PDFJS_WORKER_URL: '/${{ github.event.repository.name }}/pdfjs/pdf.worker.min.js' # Updated path here as well

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          cname: ${{ secrets.CNAME }} # Optional: Add if you have a custom domain
