name: Deploy Tax Quote Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm ls pdfjs-dist || true  # Check if pdfjs-dist is installed correctly

      - name: Debug PDF.js files
        run: |
          echo "Listing pdfjs-dist contents:"
          ls -la node_modules/pdfjs-dist/
          echo "Listing build directory:"
          ls -la node_modules/pdfjs-dist/build/
          echo "Checking for specific worker files:"
          find node_modules/pdfjs-dist -name "pdf.worker*.js"

      - name: Copy PDF Worker
        run: |
          mkdir -p public/pdfjs
          echo "Copying worker files..."
          cp node_modules/pdfjs-dist/build/pdf.worker.js public/pdfjs/ || echo "worker.js not found"
          cp node_modules/pdfjs-dist/build/pdf.worker.min.js public/pdfjs/ || echo "worker.min.js not found"
          echo "Verifying copied files:"
          ls -la public/pdfjs/

      - name: Build application
        run: |
          npm run build
        env:
          BASE_URL: '/${{ github.event.repository.name }}'

      - name: Verify dist directory
        run: |
          echo "Checking dist directory structure:"
          ls -R dist/
          echo "Checking for worker files in dist:"
          find dist -name "pdf.worker*.js"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          cname: ${{ secrets.CNAME }}
